export const GET_MEALPLAN_SUCCESS = 'GET_MEALPLAN_SUCCESS';
export const GET_MEALPLAN_FAILURE = 'GET_MEALPLAN_FAILURE';
export const SET_MEALPLAN_SUCCESS = 'SET_MEALPLAN_SUCCESS';
export const SET_MEALPLAN_FAILURE = 'SET_MEALPLAN_FAILURE';
export const SET_MEAL_TRIGGER = 'SET_MEAL_TRIGGER';
export const MEAL_DELETE_SUCCESS = 'MEAL_DELETE_SUCCESS';
export const MEAL_DELETE_FAILURE = 'MEAL_DELETE_FAILURE';