export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FALIURE = 'CREATE_JOB_FALIURE';
export const SHOW_ALL_APPLICANTS_SUCCESS = 'SHOW_ALL_APPLICANTS_SUCCESS';
export const SHOW_ALL_APPLICANTS_FAILURE = 'SHOW_ALL_APPLICANTS_FAILURE';
export const GET_APPLICANT_SUCCESS = 'GET_APPLICANT_SUCCESS';
export const GET_APPLICANT_FAILURE = 'GET_APPLICANT_FAILURE';