export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FALIURE = "CREATE_JOB_FALIURE";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FALIURE = "DELETE_JOB_FALIURE";
export const SHOW_ALL_APPLICANTS_SUCCESS = "SHOW_ALL_APPLICANTS_SUCCESS";
export const SHOW_ALL_APPLICANTS_FAILURE = "SHOW_ALL_APPLICANTS_FAILURE";
export const SEARCH_APPLICANTS_SUCCESS = "SEARCH_APPLICANTS_SUCCESS";
export const SEARCH_APPLICANTS_FAILURE = "SEARCH_APPLICANTS_FAILURE";
export const SELECT_NANNY_SUCCESS = "SELECT_NANNY_SUCCESS";
export const SELECT_NANNY_FAILURE = "SELECT_NANNY_FAILURE";
export const SEARCH_INITIATE = "SEARCH_INITIATE";
export const GET_MY_JOB_SUCCESS = "GET_MY_JOB_SUCCESS";
export const GET_MY_JOB_FAILURE = "GET_MY_JOB_FAILURE";
export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_FAILURE = "GET_ALL_JOBS_FAILURE";
export const SEARCH_JOBS_SUCCESS = "SEARCH_JOBS_SUCCESS";
export const SEARCH_JOBS_FAILURE = "SEARCH_JOBS_FAILURE";
export const APPLY_TO_JOB_SUCCESS = "APPLY_TO_JOB_SUCCESS";
export const APPLY_TO_JOB_FAILURE = "APPLY_TO_JOB_FAILURE";
export const VIEW_ALL_MY_APPLIED_JOBS_SUCCESS =
  "VIEW_ALL_MY_APPLIED_JOBS_SUCCESS";
export const VIEW_ALL_MY_APPLIED_JOBS_FAILURE =
  "VIEW_ALL_MY_APPLIED_JOBS_FAILURE";
export const EXIT_JOB_SUCCESS = "APPLY_TO_JOB_SUCCESS";
export const EXIT_JOB_FAILURE = "APPLY_TO_JOB_FAILURE";
