export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILURE = 'GET_APPOINTMENT_FAILURE';
export const SET_APPOINTMENT_SUCCESS = 'SET_APPOINTMENT_SUCCESS';
export const SET_APPOINTMENT_FAILURE = 'SET_APPOINTMENT_FAILURE';