export const GET_VACCINE_SUCCESS = 'GET_VACCINE_SUCCESS';
export const GET_VACCINE_FAILURE = 'GET_VACCINE_FAILURE';
export const SET_VACCINE_SUCCESS = 'GET_VACCINE_SUCCESS';
export const SET_VACCINE_FAILURE = 'SET_VACCINE_FAILURE';
export const VACCINE_DELETE_SUCCESS = 'VACCINE_DELETE_SUCCESS';
export const VACCINE_DELETE_FAILURE = 'VACCINE_DELETE_FAILURE';


