export const ADD_CHILD = "ADD_CHILD";
export const ADD_CHILD_SUCCESS = "ADD_CHILD_SUCCESS";
export const ADD_CHILD_FAILURE = "ADD_CHILD_FAILURE";
export const FETCH_CHILDREN = "FETCH_CHILDREN";
export const FETCH_CHILDREN_SUCCESS = "FETCH_CHILDREN_SUCCESS";
export const FETCH_CHILDREN_FAILURE = "FETCH_CHILDREN_FAILURE";
export const DELETE_CHILD_SUCCESS = "DELETE_CHILD_SUCCESS";
export const DELETE_CHILD_FAILURE = "DELETE_CHILD_FAILURE";
